site_name: DNAStream Documentation
repo_url: https://github.mdanderson.org/llweber/DNAStream
theme:
  name: material
  logo: images/logo.png 
  palette:
    - scheme: default
      primary: light blue
      accent: deep orange

nav:
  - Home: index.md
  - Design: 
    - Charter: design/CHARTER.md
    - Model: design/MODEL.md
    - Specifications: design/SPECS.md
    - Invariants: design/INVARIANTS.md
    - Registry: design/REGISTRY.md
  - API:
      # - DNAStream: api/dnastream.md
      - Registry: api/registry.md
      - Schema: api/schema.md


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          inventories: []  # Fix warning by replacing 'import' with 'inventories'
          paths: ["src"]
          options:
            docstring_style: numpy
            show_source: true