site_name: DNAStream Documentation
repo_url: https://github.mdanderson.org/llweber/DNAStream
theme:
  name: material

nav:
  - Home: index.md
  - API Reference:
      - DNAStream: api/dnastream.md

plugins:
  - mkdocstrings:
      default_handler: python